version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    command: npm start
    restart: always
    volumes:
      - ./:/usr/src/app
      # IMPORTANT: If you are using Windows, you might want to uncomment the entry below.
      # https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
      # - ./.docker_node_modules:/usr/src/app/node_modules # https://stackoverflow.com/a/32785014
    depends_on:
      - db
    ports:
      - '8080:8080'
      - '9229:9229'
    tty: true

  db:
    image: postgres:15-alpine
    user: root
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./.docker_postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8081:8080
